# https://taskfile.dev

version: '3'

includes:
  core: ./packages/core/taskfile.yml
  web: ./packages/web/taskfile.yml
  components: ./packages/components/taskfile.yml
  demo: ./apps/demo/taskfile.yml

tasks:
  install:
    aliases: [workspace]
    desc: Refresh dependency install for workspaces
    cmds:
      # - task: install:clean
      - task: install:bun

  install:clean:
    internal: true
    desc: Clean the project
    cmds:
      - rm -rf node_modules bun.lockb dist

  install:bun:
    internal: true
    desc: Install dependencies
    deps: [install:clean]
    cmds:
      - bun install

